name: Release UI Bundle Zip File
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

jobs:
  build-ui-bundle:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version : '16'
    - name: Install gulp
      run: npm install -g gulp-cli
    - name: Install dependencies
      run: npm install
    - name: Build UI bundle
      run: gulp bundle
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        body: "Antora UI bundle version v${{ github.event.inputs.release_version }}"
        tag_name: v${{ github.event.inputs.release_version }}
        draft: false
        prerelease: false
        files: build/ui-bundle.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
